const readline = require("readline-sync");
const nome = readline.question("Digite o nome do aluno: ");
const disciplina = readline.question("Digite a disciplina: ");
const nota1 = Number(readline.question("Digite a primeira nota: "));
const nota2 = Number(readline.question("Digite a segunda nota: "));
const faltas = Number(readline.question("Digite a quantidade de faltas: "));
const turma = readline.question("Digite a turma: ");
const escola = readline.question("Digite a escola: ");
const periodo = readline.question("Digite o periodo: ");
const idade = Number(readline.question("Digite a idade: "));
const carga = Number(readline.question("Digite a carga horaria: "));
const cidade = readline.question("Digite a cidade: ");
const anoletivo = readline.question("Digite o ano: ");
const media = (nota1 + nota2) / 2;

console.log("\n--- RELATÓRIO DO ALUNO ---");
console.log("Aluno:", nome);
console.log("Disciplina:", disciplina);
console.log("Nota 1:", nota1);
console.log("Nota 2:", nota2);
console.log("Média:", media);
console.log("Faltas:", faltas);
console.log("Turma:", turma);   
console.log("Escola:", escola);
console.log("Período:", periodo);
console.log("Idade:", idade);
console.log("Carga horária:", carga);
console.log("Cidade:", cidade);
console.log("Ano letivo:", anoletivo);